before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  ldflags: -s -w -X github.com/dm3ch/git-profile-manager/version.VersionNumber={{.Version}} -X github.com/dm3ch/git-profile-manager/version.VersionCommitHash={{.Commit}} -X github.com/dm3ch/git-profile-manager/version.VersionBuildDate={{.Date}}
  goarch:
    - amd64
  goos:
    - darwin
    - linux
    - windows

universal_binaries:
  - replace: true

archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

brews:
- name: "git-profile-manager"
  github:
    owner: dm3ch
    name: homebrew-tap
  commit_author:
    name: dm3ch-ci
    email: dm3ch+ci@dm3ch.net
  folder: Formula
  caveats: "git-profile-manager --help"
  homepage: "https://github.com/dm3ch/git-profile-manager"
  description: "Allows to manage and switch between multiple git profiles"
  custom_block: |
    head "https://github.com/dm3ch/git-profile-manager.git"
  dependencies:
    - git
  test: |
    system "#{bin}/git-profile-manager", "--version"
  install: |
    ln_s "git-profile-manager", "git-profile"
    bin.install "git-profile-manager"
    bin.install "git-profile"

    system "#{bin}/git-profile-manager completion bash > bash_completion.bash"
    system "#{bin}/git-profile-manager completion zsh > zsh_completion.zsh"
    bash_completion.install "bash_completion.bash"
    zsh_completion.install "zsh_completion.zsh"
